import React, { FunctionComponent } from "react";
import { Checkbox as AntCheckbox } from "antd";
import { FormItem } from "@components/FormItem";
import { FormItemProps } from "antd/lib/form";

interface CheckboxProps {
	label: string;
	/**
	 * The prompt message. If not provided, the prompt message will be generated by the validation rule.
	 */
	help?: FormItemProps["help"];
	/**
	 * Optional description to provide more information about the input
	 */
	description?: string;
	/**
	 * Form item name
	 */
	name?: FormItemProps["name"];
}

export const Checkbox: FunctionComponent<CheckboxProps> = ({ label, description, name, help }) => {
	return (
		<FormItem description={description} name={name} help={help} valuePropName="checked">
			<AntCheckbox>
				<span className="text-base font-medium">{label}</span>
			</AntCheckbox>
		</FormItem>
	);
};
