name: CICD

on:
  push:
    branches:
      - localnet
      - devnet
      - mainnet
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]')
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v2

      - name: Initialise CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: javascript

      # Analysis
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install
      - name: Use Node.js 14.17
        uses: actions/setup-node@v1
        with:
          node-version: 14.17
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Run yarn install
        run: yarn install

      # Linting
      - name: Run linter
        run: yarn run lint

      # Testing
      - name: Run unit tests
        run: yarn run test:unit
